name: example
description: example of dio log
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  dio: ^4.0.0
  gp_dio_log:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  module:
    androidX: false
    androidPackage: com.rich.example
    iosBundleIdentifier: com.rich.example
