name: gp_dio_log
description: HTTP Inspector tool for Dart which can debugging http requests，Currently, DIO based HTTP capture is implemented.
version: 4.0.0
homepage: https://github.com/flutterplugin/gp_dio_log

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  intl: ^0.17.0

dev_dependencies: 
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
